# Generated by Django 4.0 on 2021-12-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Leer Post 👉', max_length=255),
        ),
    ]
